### PR TITLE
show wrapped coordinates in mouse-position example

### LINKED ISSUE #45: update mouse position example to show wrapped coordinates
https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/

gives bad longitudes as you cross over the dateline

https://jsfiddle.net/u8cowx7g/ is my ugly fix, maybe you guys have a better one?

### PR DESCRIPTION
**Pull request by andrewharvey**
closes #45

### CODE REVIEW

**Comment by andrewharvey** [comment]
Looks like I don't have the same level of permissions here as mapbox-gl-js, "You’re not authorized to merge this pull request."

**Comment by mourner** [comment]
@andrewharvey that's really weird! You have the same permissions set as in the main repo:

image

**Comment by colleenmcginnis** [comment]
@mourner @andrewharvey I think it's the `publisher-production` branch protections. I couldn't see how they were set up in the other repo. @mourner feel free to adjust!

**Comment by chloekraw** [comment]
hey @andrewharvey, I think it looks like our company security policies have changed and it's not going to be possible to give you merge permissions on new repos, but please feel free to ping me anytime if we're blocking you on merges. thanks for the contribution!

**Comment by mourner** [comment]
@andrewharvey to be clear, as far as I understand, this is specifically only for branches that immediately go live on our website — you can merge in other cases like the `mapbox-gl-js` repo.

**Comment by andrewharvey** [comment]
> hey @andrewharvey, I think it looks like our company security policies have changed and it's not going to be possible to give you merge permissions on new repos, but please feel free to ping me anytime if we're blocking you on merges. thanks for the contribution!

> @andrewharvey to be clear, as far as I understand, this is specifically only for branches that immediately go live on our website — you can merge in other cases like the mapbox-gl-js repo.

Okay that's fair enough, it's your call. In the past I could merge to publisher-production in gl-js which went live straight away, but not a big deal.

**Pull request merged**
