### PR TITLE
s/v4.5.1/v4.7.0

### PR DESCRIPTION
**Pull request by tristen**

### CODE REVIEW

**Comment by scottsfarley93** [comment]
@tristen changes look good but I'm not seeing the files on the CDN -- https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css returns a 404 Not Found for me. Did you upload those assets after publishing the npm package?

**Comment by tristen** [comment]
Hmm @scottsfarley93 so following the instructions [you linked me too](https://github.com/mapbox/mapbox-gl-draw/issues/608#issuecomment-285509748) I am running this command:

```sh
aws s3 cp --recursive --acl public-read dist s3://mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0
```

But it's returning a _Could not connect to the endpoint URL_ error

```log
upload failed: dist/mapbox-gl-geocoder.css to s3://mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css Could not connect to the endpoint URL: "https://mapbox-gl-js.s3.local.amazonaws.com/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css"
upload failed: dist/mapbox-gl-geocoder.min.js to s3://mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js Could not connect to the endpoint URL: "https://mapbox-gl-js.s3.local.amazonaws.com/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js"
```

I'm running this command from a console which _should_ have the environment variables set. I also seem to get all the right responses when trying the instructions here: https://aws.amazon.com/premiumsupport/knowledge-center/s3-could-not-connect-endpoint-url/ I'm a bit perplexed by this 🤔

**Comment by colleenmcginnis** [comment]
@scottsfarley93 @tristen was this resolved?

**Comment by tristen** [comment]
👋 @colleenmcginnis looks like these exist now

`https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.min.js`
`https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.7.0/mapbox-gl-geocoder.css`

So this PR should be mergable.

**Review by katydecorah — APPROVED** [review]

**Pull request merged**
